### ISSUE TITLE
What middleware would you like to see?

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#449]
Let us know what kinds of middleware you'd like to see supported by Assemble. This includes template engines, anything goes!

### List from comments below
- [ ] [Blog Post Index Pages](https://github.com/assemble/assemble/issues/449#issuecomment-35752112)
- [ ] [Asset Cache Busting / Processing](https://github.com/assemble/assemble/issues/449#issuecomment-35966908) ([tracking Issue](https://github.com/assemble/assemble/issues/450))
- [ ] [breadcrumbs](https://github.com/assemble/assemble/issues/449#issuecomment-36306914)
- [ ] [Navigation](https://github.com/assemble/assemble/issues/449#issuecomment-37105117) ([tracking Issue](https://github.com/assemble/assemble/issues/462))
- [ ] collections
- [ ] sorting and filtering
- [ ] drafts (also `published` etc). see (https://github.com/assemble/assemble/issues/170, https://github.com/assemble/assemble/issues/169)
- [ ] dummy data ([tracking issue](https://github.com/assemble/assemble/issues/523))

**Comment by jonschlinkert** [comment]
closing due to age

**Comment by criticalmash** [comment]
Hi,

not sure where the appropriate place is to post this announcement (let me know if I should post this somewhere else). But after two years, I've finally published my Navigation middleware, [assemble-navigation](https://github.com/criticalmash/assemble-navigation).

It's able to create a navigation system with multiple hierarchal menu data objects that are passed to your templates for rendering out menus as you see fit. Possibilities include dropdown menus, mobile menus, sidebars, whatever you can think of.

I've also published a collection of template helpers named [navigation-helpers](https://github.com/criticalmash/navigation-helpers). Right now there are two helpers, one for filtering and ordering menu items, another to help create breadcrumbs.

So, we can check Navigation and Breadcrumbs off the list : )

Thanks @doowb and @jonschlinkert for answering all my Assemble questions,
John

**Comment by jonschlinkert** [comment]
that is awesome! I can't wait to take it for a test drive! Good timing too, we're working on new websites for assemble, verb, update and generate.

**Comment by criticalmash** [comment]
Yes please do. I'd loved some feedback on how to improve it.
